// Image pools — reused across projects where appropriate
const GOLF = [
  'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=1200&q=80',
  'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=1200&q=80',
  'https://images.unsplash.com/photo-1592919505780-303950717480?w=1200&q=80',
  'https://images.unsplash.com/photo-1567016526105-22da7c13161a?w=1200&q=80',
  'https://images.unsplash.com/photo-1611374243147-44a702c2d44c?w=1200&q=80',
  'https://images.unsplash.com/photo-1600166898405-da9535204843?w=1200&q=80',
  'https://images.unsplash.com/photo-1574015974293-817f0ebebb74?w=1200&q=80',
  'https://images.unsplash.com/photo-1561049501-e1f96bdd98fd?w=1200&q=80',
  'https://images.unsplash.com/photo-1580477667995-2b94f01c9516?w=1200&q=80',
  'https://images.unsplash.com/photo-1542683581-0e1d3a30f06b?w=1200&q=80',
];
const RESORT = [
  'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=80',
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80',
  'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80',
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
  'https://images.unsplash.com/photo-1439130490301-25e322d88054?w=1200&q=80',
  'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&q=80',
  'https://images.unsplash.com/photo-1530092285049-1c42085fd395?w=1200&q=80',
  'https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=1200&q=80',
];
const URBAN = [
  'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=1200&q=80',
  'https://images.unsplash.com/photo-1567942711641-5f0e7d557629?w=1200&q=80',
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&q=80',
  'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80',
  'https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=1200&q=80',
  'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80',
  'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=1200&q=80',
];
const GARDEN = [
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
  'https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=1200&q=80',
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&q=80',
  'https://images.unsplash.com/photo-1504198458649-3128b932f49e?w=1200&q=80',
  'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=1200&q=80',
];
const ARTWORK = [
  'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=1200&q=80',
  'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=1200&q=80',
  'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
  'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=1200&q=80',
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
  'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80',
];

export const projects = [
  // ── GOLF ──────────────────────────────────────────────────────────────────
  {
    id: 'golf-brg-danang',
    slug: 'golf-brg-danang',
    title: 'Sân Golf BRG Đà Nẵng',
    titleEn: 'BRG Da Nang Golf Course',
    category: 'Golf',
    location: 'Đà Nẵng',
    area: '—',
    duration: '—',
    client: 'BRG Group',
    year: '2015',
    image: GOLF[0].replace('w=1200', 'w=800'),
    images: [GOLF[0], GOLF[1], GOLF[2], GOLF[3], GOLF[4], GOLF[5]],
    description: 'Thi công cảnh quan và hệ thống tưới tiêu tự động Rainbird cho 18 lỗ golf BRG tại Đà Nẵng — đạt tiêu chuẩn quốc tế về cỏ và hệ thống tưới.',
    descriptionEn: 'Landscape construction and Rainbird automatic irrigation for all 18 holes of BRG Da Nang Golf Course — meeting international turf and irrigation standards.',
    articles: [],
  },
  {
    id: 'golf-bana-suoi-mo',
    slug: 'golf-bana-suoi-mo',
    title: 'Sân Golf Bà Nà – Suối Mơ',
    titleEn: 'Ba Na Hills – Suoi Mo Golf Course',
    category: 'Golf',
    location: 'Đà Nẵng',
    area: '—',
    duration: '—',
    client: 'Sun Group',
    year: '2017',
    image: GOLF[1].replace('w=1200', 'w=800'),
    images: [GOLF[1], GOLF[4], GOLF[7], GOLF[8], GOLF[0], GOLF[9]],
    description: 'Thi công cảnh quan và hệ thống tưới tiêu cho sân golf Bà Nà – Suối Mơ trong quần thể khu du lịch Bà Nà Hills của Sun Group.',
    descriptionEn: "Landscape construction and irrigation systems for the Ba Na Hills – Suoi Mo Golf Course within Sun Group's Ba Na Hills resort complex.",
    articles: [],
  },
  {
    id: 'golf-laguna-lang-co',
    slug: 'golf-laguna-lang-co',
    title: 'Sân Golf Laguna Lăng Cô',
    titleEn: 'Laguna Lăng Cô Golf Course',
    category: 'Golf',
    location: 'Thừa Thiên Huế',
    area: '—',
    duration: '—',
    client: 'Laguna Vietnam',
    year: '2016',
    image: GOLF[2].replace('w=1200', 'w=800'),
    images: [GOLF[2], GOLF[3], GOLF[8], GOLF[1], GOLF[6], GOLF[5]],
    description: 'Cảnh quan và hệ thống tưới tiêu Rainbird cho sân golf 18 lỗ tại khu nghỉ dưỡng Laguna Lăng Cô — kết hợp giữa cảnh quan tự nhiên và tiêu chuẩn thi đấu quốc tế.',
    descriptionEn: '18-hole golf course landscape and Rainbird irrigation at Laguna Lăng Cô Resort — blending natural scenery with international tournament standards.',
    articles: [],
  },
  {
    id: 'golf-clb-danang',
    slug: 'golf-clb-danang',
    title: 'Câu Lạc Bộ Golf Đà Nẵng (The Dunes)',
    titleEn: 'Da Nang Golf Club – The Dunes',
    category: 'Golf',
    location: 'Ngũ Hành Sơn, Đà Nẵng',
    area: '—',
    duration: '—',
    client: 'VinaCapital',
    year: '2010',
    image: GOLF[4].replace('w=1200', 'w=800'),
    images: [GOLF[4], GOLF[7], GOLF[9], GOLF[0], GOLF[5], GOLF[1]],
    description: 'Thi công cảnh quan và bảo dưỡng sân golf The Dunes — một trong những sân golf ven biển đẳng cấp nhất miền Trung Việt Nam.',
    descriptionEn: 'Landscape construction and maintenance for The Dunes golf course — one of the finest beachside golf courses in Central Vietnam.',
    articles: [],
  },
  {
    id: 'golf-montgomerie-links',
    slug: 'golf-montgomerie-links',
    title: 'Sân Golf Montgomerie Links',
    titleEn: 'Montgomerie Links Golf Course',
    category: 'Golf',
    location: 'Điện Bàn, Quảng Nam',
    area: '—',
    duration: '—',
    client: 'VinaCapital / Montgomerie Links Vietnam',
    year: '2012',
    image: GOLF[6].replace('w=1200', 'w=800'),
    images: [GOLF[6], GOLF[3], GOLF[5], GOLF[9], GOLF[2], GOLF[8]],
    description: 'Thi công cảnh quan và thảm cỏ cho sân golf 18 lỗ Montgomerie Links — thiết kế bởi huyền thoại Colin Montgomerie, nằm giữa đồng bằng ven biển Quảng Nam.',
    descriptionEn: 'Turf and landscape construction for the 18-hole Montgomerie Links course — designed by legend Colin Montgomerie, set among the coastal plains of Quang Nam.',
    articles: [],
  },
  {
    id: 'golf-flc-quy-nhon',
    slug: 'golf-flc-quy-nhon',
    title: 'Sân Golf FLC Quy Nhơn',
    titleEn: 'FLC Quy Nhon Golf Course',
    category: 'Golf',
    location: 'Quy Nhơn, Bình Định',
    area: '—',
    duration: '—',
    client: 'FLC Group',
    year: '2019',
    image: GOLF[8].replace('w=1200', 'w=800'),
    images: [GOLF[8], GOLF[0], GOLF[5], GOLF[7], GOLF[3], GOLF[6]],
    description: 'Cảnh quan và hệ thống tưới tự động cho sân golf ven biển FLC Quy Nhơn — tích hợp cảnh quan biển và thảm cỏ Zoysia đạt tiêu chuẩn thi đấu.',
    descriptionEn: 'Landscape and automatic irrigation for FLC Quy Nhon beachside golf course — integrating coastal scenery with tournament-grade Zoysia turf.',
    articles: [],
  },

  // ── RESORT ────────────────────────────────────────────────────────────────
  {
    id: 'laguna-lang-co',
    slug: 'laguna-lang-co',
    title: 'Khu Nghỉ Dưỡng Laguna Lăng Cô',
    titleEn: 'Laguna Lăng Cô Resort',
    category: 'Resort',
    location: 'Phú Lộc, Thừa Thiên Huế',
    area: '280 ha',
    duration: '—',
    client: 'Laguna Vietnam',
    year: '2013',
    image: RESORT[0].replace('w=1200', 'w=800'),
    images: [RESORT[0], RESORT[1], RESORT[2], RESORT[3], RESORT[7], GARDEN[1]],
    description: 'Thiết kế và thi công cảnh quan toàn bộ khu nghỉ dưỡng Laguna Lăng Cô rộng 280 ha — cảnh quan resort, vườn biệt thự và hành lang cây xanh dọc bãi biển.',
    descriptionEn: 'Full landscape design and construction for the 280-ha Laguna Lăng Cô Resort — resort greenery, villa gardens, and beachfront green corridors.',
    articles: [],
  },
  {
    id: 'ocean-villas-danang',
    slug: 'ocean-villas-danang',
    title: 'The Ocean Villas Đà Nẵng',
    titleEn: 'The Ocean Villas Da Nang',
    category: 'Resort',
    location: 'Ngũ Hành Sơn, Đà Nẵng',
    area: '150 ha',
    duration: '—',
    client: 'VinaCapital',
    year: '2014',
    image: RESORT[1].replace('w=1200', 'w=800'),
    images: [RESORT[1], RESORT[2], RESORT[4], RESORT[3], GARDEN[0], RESORT[8]],
    description: 'Cảnh quan biệt thự nghỉ dưỡng cao cấp The Ocean Villas — thiết kế vườn riêng từng căn biệt thự, hồ bơi infinity và hành lang cây xanh nội khu.',
    descriptionEn: 'Premium resort villa landscaping at The Ocean Villas — individual villa gardens, infinity pools, and internal green corridors.',
    articles: [],
  },
  {
    id: 'fiore-phan-thiet',
    slug: 'fiore-phan-thiet',
    title: 'Fiore Healthy Phan Thiết Resort',
    titleEn: 'Fiore Healthy Phan Thiet Resort',
    category: 'Resort',
    location: 'Phan Thiết, Bình Thuận',
    area: '1.8 ha',
    duration: '—',
    client: 'Công ty CP Du Lịch Ngọc Sơn',
    year: '2021',
    image: RESORT[2].replace('w=1200', 'w=800'),
    images: [RESORT[2], RESORT[0], GARDEN[1], RESORT[5], RESORT[8], GARDEN[3]],
    description: 'Thiết kế và thi công cảnh quan khu nghỉ dưỡng Fiore Healthy tại Phan Thiết — cảnh quan nhiệt đới, vườn wellness và không gian nghỉ dưỡng xanh hài hòa.',
    descriptionEn: 'Landscape design and construction for Fiore Healthy Resort, Phan Thiet — tropical landscaping, wellness garden, and harmonious green resort spaces.',
    articles: [],
  },
  {
    id: 'movenpick-novaworld',
    slug: 'movenpick-novaworld',
    title: 'Khách Sạn Movenpick Novaworld Phan Thiết',
    titleEn: 'Movenpick Hotel Novaworld Phan Thiet',
    category: 'Resort',
    location: 'Phan Thiết',
    area: '—',
    duration: '—',
    client: 'Delta-Valley Binh Thuan',
    year: '2022',
    image: RESORT[3].replace('w=1200', 'w=800'),
    images: [RESORT[3], RESORT[4], RESORT[7], RESORT[1], RESORT[8], GARDEN[2]],
    description: 'Cảnh quan khách sạn Movenpick thuộc quần thể Novaworld Phan Thiết — thiết kế và thi công hành lang cây xanh, pool garden và sân vườn sảnh đón.',
    descriptionEn: 'Landscape works for Movenpick Hotel within the Novaworld Phan Thiet complex — green corridors, pool garden, and lobby forecourt landscaping.',
    articles: [],
  },
  {
    id: 'hoiana-maintenance',
    slug: 'hoiana-maintenance',
    title: 'HOIANA – Bảo Dưỡng Cảnh Quan',
    titleEn: 'HOIANA Resort Landscape Maintenance',
    category: 'Resort',
    location: 'Hội An, Quảng Nam',
    area: '—',
    duration: '—',
    client: 'HOIANA',
    year: '2021',
    image: RESORT[5].replace('w=1200', 'w=800'),
    images: [RESORT[5], RESORT[6], RESORT[7], RESORT[0], RESORT[8], GARDEN[4]],
    description: 'Dịch vụ bảo dưỡng cảnh quan dài hạn cho khu nghỉ dưỡng HOIANA tại Hội An — duy trì chất lượng cây xanh, thảm cỏ và hệ sinh thái cảnh quan toàn khu.',
    descriptionEn: "Long-term landscape maintenance services for HOIANA Resort, Hoi An — maintaining greenery quality, turf, and the resort's complete landscape ecosystem.",
    articles: [],
  },
  {
    id: 'intercontinental-danang',
    slug: 'intercontinental-danang',
    title: 'InterContinental Đà Nẵng Sun Peninsula',
    titleEn: 'InterContinental Da Nang Sun Peninsula',
    category: 'Resort',
    location: 'Sơn Trà, Đà Nẵng',
    area: '39 ha',
    duration: '—',
    client: 'Sun Group',
    year: '2014',
    image: RESORT[6].replace('w=1200', 'w=800'),
    images: [RESORT[6], RESORT[0], RESORT[4], GARDEN[0], RESORT[2], RESORT[7]],
    description: 'Thi công cảnh quan nhiệt đới cho khu nghỉ dưỡng 5 sao InterContinental trên bán đảo Sơn Trà — cảnh quan hoà nhập với rừng nhiệt đới tự nhiên.',
    descriptionEn: 'Tropical landscape construction for the 5-star InterContinental resort on Son Tra Peninsula — landscaping integrated with the natural tropical forest.',
    articles: [],
  },
  {
    id: 'fusion-resort-cam-ranh',
    slug: 'fusion-resort-cam-ranh',
    title: 'Fusion Resort Cam Ranh',
    titleEn: 'Fusion Resort Cam Ranh',
    category: 'Resort',
    location: 'Cam Ranh, Khánh Hòa',
    area: '—',
    duration: '—',
    client: 'Fusion Resorts',
    year: '2018',
    image: RESORT[8].replace('w=1200', 'w=800'),
    images: [RESORT[8], RESORT[1], GARDEN[1], RESORT[5], RESORT[3], GARDEN[5]],
    description: 'Thiết kế và thi công cảnh quan resort all-spa Fusion tại Cam Ranh — vườn thiền, đường dạo ven biển và không gian cây xanh hài hòa với kiến trúc.',
    descriptionEn: 'Landscape design and construction for Fusion Resort Cam Ranh — zen garden, beachside walkways, and greenery harmonising with the architecture.',
    articles: [],
  },

  // ── URBAN ─────────────────────────────────────────────────────────────────
  {
    id: 'hue-traffic-landscape',
    slug: 'hue-traffic-landscape',
    title: 'Cảnh Quan Đường Giao Thông TP Huế',
    titleEn: 'Hue City Traffic Road Landscape',
    category: 'Urban',
    location: 'TP Huế, Thừa Thiên Huế',
    area: '—',
    duration: '—',
    client: 'Ban Môi Trường & Đô Thị Huế',
    year: '2015',
    image: URBAN[0].replace('w=1200', 'w=800'),
    images: [URBAN[0], URBAN[1], URBAN[2], URBAN[3], URBAN[4], URBAN[5]],
    description: 'Cảnh quan hoá các tuyến đường giao thông trọng điểm của thành phố Huế — trồng cây, thảm cỏ, hoa và thiết kế dải phân cách đô thị xanh.',
    descriptionEn: 'Landscaping of key traffic roads in Hue City — tree planting, turf, flowers, and green median strip design across major urban corridors.',
    articles: [],
  },
  {
    id: 'ngu-ha-river-hue',
    slug: 'ngu-ha-river-hue',
    title: 'Cải Tạo Sông Ngự Hà TP Huế',
    titleEn: 'Ngu Ha River Renovation, Hue City',
    category: 'Urban',
    location: 'TP Huế',
    area: '—',
    duration: '—',
    client: 'Ban Môi Trường & Đô Thị Huế',
    year: '2018',
    image: URBAN[1].replace('w=1200', 'w=800'),
    images: [URBAN[1], URBAN[0], URBAN[5], URBAN[6], URBAN[7], URBAN[2]],
    description: 'Cải tạo và cảnh quan hoá dọc bờ sông Ngự Hà — tạo hành lang xanh đô thị, lối đi bộ ven sông và không gian công cộng mới cho người dân Huế.',
    descriptionEn: 'Renovation and landscaping along the Ngu Ha River bank — creating an urban green corridor, riverside walkways, and new public spaces for Hue residents.',
    articles: [],
  },
  {
    id: 'manor-crown-hue',
    slug: 'manor-crown-hue',
    title: 'The Manor Crown Huế',
    titleEn: 'The Manor Crown Hue',
    category: 'Urban',
    location: 'Huế',
    area: '—',
    duration: '—',
    client: 'BIM Group',
    year: '2019',
    image: URBAN[2].replace('w=1200', 'w=800'),
    images: [URBAN[2], URBAN[3], URBAN[4], URBAN[5], GARDEN[1], URBAN[6]],
    description: 'Thiết kế và thi công cảnh quan khu đô thị cao cấp The Manor Crown tại Huế — cảnh quan nội khu, vườn công cộng và cây xanh đường nội bộ.',
    descriptionEn: 'Landscape design and construction for The Manor Crown premium urban development in Hue — internal landscape, public gardens, and street trees.',
    articles: [],
  },
  {
    id: 'vinpearl-phu-quoc-urban',
    slug: 'vinpearl-phu-quoc-urban',
    title: 'Khu Đô Thị Vinpearl Phú Quốc',
    titleEn: 'Vinpearl Phu Quoc Urban Development',
    category: 'Urban',
    location: 'Phú Quốc, Kiên Giang',
    area: '—',
    duration: '—',
    client: 'Vingroup',
    year: '2020',
    image: URBAN[4].replace('w=1200', 'w=800'),
    images: [URBAN[4], URBAN[6], URBAN[7], URBAN[0], GARDEN[2], URBAN[3]],
    description: 'Cảnh quan đô thị cho khu phức hợp Vinpearl tại Phú Quốc — trồng cây đường phố, công viên nội khu và hành lang xanh kết nối các tiện ích.',
    descriptionEn: 'Urban landscaping for the Vinpearl complex in Phu Quoc — street trees, internal parks, and green corridors connecting amenities.',
    articles: [],
  },

  // ── CONSTRUCTION ──────────────────────────────────────────────────────────
  {
    id: 'casamia-hoi-an',
    slug: 'casamia-hoi-an',
    title: 'Khu Đô Thị Casamia Hội An',
    titleEn: 'Casamia Hoi An Urban Area',
    category: 'Construction',
    location: 'Cẩm Thanh, Hội An, Quảng Nam',
    area: '6.4 ha',
    duration: '—',
    client: 'Đạt Phương Corp',
    year: '2020',
    image: URBAN[3].replace('w=1200', 'w=800'),
    images: [URBAN[3], URBAN[4], GARDEN[1], GARDEN[0], URBAN[1], URBAN[7]],
    description: 'Thi công cảnh quan và hạ tầng xanh cho khu đô thị Casamia tại Hội An — cảnh quan đường nội khu, công viên trung tâm và hành lang cây xanh 6.4 ha.',
    descriptionEn: 'Landscape and green infrastructure construction for the Casamia urban development in Hoi An — internal road landscaping, central park, and 6.4-ha green corridors.',
    articles: [],
  },
  {
    id: 'seava-ho-tram',
    slug: 'seava-ho-tram',
    title: 'Seava Hồ Tràm Strip',
    titleEn: 'Seava Ho Tram Strip',
    category: 'Construction',
    location: 'Hồ Tràm, Bà Rịa - Vũng Tàu',
    area: '—',
    duration: '—',
    client: 'Seava',
    year: '2021',
    image: GARDEN[3].replace('w=1200', 'w=800'),
    images: [GARDEN[3], RESORT[4], GARDEN[0], URBAN[5], RESORT[7], GARDEN[5]],
    description: 'Thi công cảnh quan và cây xanh cho tổ hợp Seava tại Hồ Tràm — cảnh quan ven biển, hệ thống tưới nhỏ giọt và vườn cây nhiệt đới đặc trưng.',
    descriptionEn: 'Landscape and planting works for the Seava Ho Tram complex — coastal landscaping, drip irrigation, and signature tropical garden.',
    articles: [],
  },
  {
    id: 'sunbay-park-ninh-thuan',
    slug: 'sunbay-park-ninh-thuan',
    title: 'Sun Bay Park Ninh Thuận',
    titleEn: 'Sun Bay Park Ninh Thuan',
    category: 'Construction',
    location: 'Ninh Thuận',
    area: '—',
    duration: '—',
    client: 'Sun Group',
    year: '2023',
    image: URBAN[6].replace('w=1200', 'w=800'),
    images: [URBAN[6], URBAN[7], GARDEN[4], GARDEN[1], RESORT[6], URBAN[4]],
    description: 'Thi công cảnh quan khu nghỉ dưỡng và công viên Sun Bay tại Ninh Thuận — hệ thống tưới thông minh, vườn xương rồng và cảnh quan sa mạc nhiệt đới.',
    descriptionEn: 'Landscape construction for Sun Bay Park resort in Ninh Thuan — smart irrigation, cactus garden, and tropical desert landscaping.',
    articles: [],
  },

  // ── ARTWORK ───────────────────────────────────────────────────────────────
  {
    id: 'cau-dat-farm-dalat',
    slug: 'cau-dat-farm-dalat',
    title: 'Cầu Đất Farm – Đà Lạt',
    titleEn: 'Cau Dat Farm – Da Lat',
    category: 'Artwork',
    location: 'Trạm Hành, Đà Lạt, Lâm Đồng',
    area: '230 ha',
    duration: '—',
    client: 'Novaland / Cau Dat Tea JSC',
    year: '2022',
    image: GARDEN[0].replace('w=1200', 'w=800'),
    images: [GARDEN[0], GARDEN[2], GARDEN[3], GARDEN[4], GARDEN[5], GARDEN[6]],
    description: 'Thi công cảnh quan và artwork cho khu nông trại sinh thái Cầu Đất rộng 230 ha tại Đà Lạt — công trình nghệ thuật iconic hoà quyện với địa hình đồi chè.',
    descriptionEn: 'Landscape and artwork construction for the 230-ha Cau Dat eco-farm in Da Lat — iconic art installations blending with the tea-plantation terrain.',
    articles: [],
  },
  {
    id: 'tropicana-novaworld',
    slug: 'tropicana-novaworld',
    title: 'The Tropicana – Novaworld Hồ Tràm',
    titleEn: 'The Tropicana – Novaworld Ho Tram',
    category: 'Artwork',
    location: 'Hồ Tràm, Bà Rịa - Vũng Tàu',
    area: '—',
    duration: '—',
    client: 'Novaland',
    year: '2022',
    image: ARTWORK[0].replace('w=1200', 'w=800'),
    images: [ARTWORK[0], ARTWORK[1], ARTWORK[2], ARTWORK[3], ARTWORK[4], ARTWORK[5]],
    description: 'Thi công cảnh quan và công trình Artwork biểu tượng cho khu The Tropicana tại Novaworld Hồ Tràm — tạo dấu ấn nhận diện độc đáo cho dự án nghỉ dưỡng ven biển.',
    descriptionEn: 'Landscape and iconic Artwork construction for The Tropicana at Novaworld Ho Tram — creating a unique landmark identity for the beachside resort development.',
    articles: [],
  },
  {
    id: 'sunworld-bana-hills',
    slug: 'sunworld-bana-hills',
    title: 'Sun World Bà Nà Hills – Artwork Cảnh Quan',
    titleEn: 'Sun World Ba Na Hills – Landscape Artwork',
    category: 'Artwork',
    location: 'Đà Nẵng',
    area: '—',
    duration: '—',
    client: 'Sun Group',
    year: '2020',
    image: ARTWORK[2].replace('w=1200', 'w=800'),
    images: [ARTWORK[2], ARTWORK[4], ARTWORK[1], GARDEN[2], ARTWORK[5], ARTWORK[3]],
    description: 'Thi công các hạng mục Artwork và cảnh quan đặc biệt tại Sun World Bà Nà Hills — tạo điểm nhấn nghệ thuật iconic trong không gian giải trí độc đáo.',
    descriptionEn: 'Construction of Artwork and special landscape features at Sun World Ba Na Hills — creating iconic artistic highlights in a unique entertainment landscape.',
    articles: [],
  },
  {
    id: 'hoiana-artwork',
    slug: 'hoiana-artwork',
    title: 'HOIANA – Artwork & Cảnh Quan Đặc Biệt',
    titleEn: 'HOIANA – Artwork & Feature Landscape',
    category: 'Artwork',
    location: 'Hội An, Quảng Nam',
    area: '—',
    duration: '—',
    client: 'HOIANA',
    year: '2022',
    image: ARTWORK[4].replace('w=1200', 'w=800'),
    images: [ARTWORK[4], ARTWORK[0], ARTWORK[3], RESORT[5], ARTWORK[2], GARDEN[3]],
    description: 'Thiết kế và thi công các công trình Artwork cảnh quan đặc biệt cho khu nghỉ dưỡng HOIANA — kết hợp nghệ thuật đương đại và văn hóa địa phương Hội An.',
    descriptionEn: 'Design and construction of feature Artwork for HOIANA Resort — blending contemporary art with the local culture and heritage of Hoi An.',
    articles: [],
  },

];

export const timelineItems = [
  {
    year: '2007–2008',
    title: 'Khởi nghiệp',
    titleEn: 'Founding',
    description: 'Khởi đầu bằng nhập khẩu và phân phối hoa, cung ứng lao động cảnh quan mềm (cây, hoa, thảm cỏ).',
    descriptionEn: 'Started with flower import/distribution and soft landscape labour supply — trees, flowers, and turf.',
  },
  {
    year: '2009–2013',
    title: 'Hình thành và phát triển',
    titleEn: 'Formation & Growth',
    description: 'Xây dựng đội ngũ nhân lực, đầu tư vườn ươm, thiết lập quan hệ đối tác với các tập đoàn bất động sản lớn.',
    descriptionEn: 'Built a skilled workforce, invested in a plant nursery, and established partnerships with major real estate groups.',
  },
  {
    year: '2014–2018',
    title: 'Mở rộng dịch vụ',
    titleEn: 'Service Expansion',
    description: 'Mở rộng sang hạ tầng, cảnh quan cứng, hệ thống tưới tiêu. Khai trương văn phòng Huế, phát triển thị trường miền Trung.',
    descriptionEn: 'Expanded into infrastructure, hardscape, and irrigation systems. Opened Hue office and grew the Central Vietnam market.',
  },
  {
    year: '2018–2022',
    title: 'Nhà thầu chính đa lĩnh vực',
    titleEn: 'Full-Service Main Contractor',
    description: 'Trở thành tổng thầu thiết kế + thi công. Mở rộng sang MEP, nghệ thuật công trình và hợp tác ASEAN.',
    descriptionEn: 'Became main contractor for full design+build. Expanded into MEP, artwork installation, and ASEAN cooperation.',
  },
  {
    year: '2023–nay',
    title: 'Tăng trưởng bền vững',
    titleEn: 'Sustainable Growth',
    description: 'Tái cơ cấu tổ chức, áp dụng tiêu chuẩn ISO, đầu tư hệ thống CNTT và tăng cường đối tác golf–cảnh quan.',
    descriptionEn: 'Restructured the organisation, applied ISO standards, invested in IT systems, and strengthened golf-landscape partnerships.',
  },
];

export const partners = [
  { name: 'VinaCapital' },
  { name: 'Novaland' },
  { name: 'BRG Group' },
  { name: 'Laguna Lăng Cô' },
  { name: 'Sun Group' },
  { name: 'Hung Thinh Corp' },
  { name: 'Fusion Resort' },
  { name: 'HOIANA' },
  { name: 'Radisson' },
  { name: 'Minor International' },
  { name: 'Obayashi Vietnam' },
  { name: 'Vicoland Group' },
  { name: 'Dat Phuong' },
  { name: 'TTC Land' },
  { name: 'Sacomreal' },
  { name: 'Six Senses' },
  { name: 'Marriott' },
  { name: 'Hyatt' },
  { name: 'Seava Hồ Tràm' },
  { name: 'TonkinLand' },
];

export const memberCompanies = [
  {
    abbr: 'LAPLA',
    name: 'LAPLA',
    tagline: 'Lawn & Landscaping',
    description: 'Chuyên thiết kế cảnh quan và sân golf',
    descriptionEn: 'Landscape design and golf course specialists',
    accent: '#16a34a',
  },
  {
    abbr: 'ANA',
    name: 'An Nguyen An (ANA) Construction',
    tagline: 'Construction & MEP',
    description: 'Thi công xây dựng và cơ điện',
    descriptionEn: 'Civil construction and MEP works',
    accent: '#2563eb',
  },
  {
    abbr: 'TCA',
    name: 'Tuan Cuong Art',
    tagline: 'Artwork & Iconic Installations',
    description: 'Thi công Artwork và Iconic',
    descriptionEn: 'Artwork fabrication and iconic installations',
    accent: '#7c3aed',
  },
  {
    abbr: 'BHA',
    name: 'BHA Architecture',
    tagline: 'Architecture & Landscape Design',
    description: 'Thiết kế kiến trúc và cảnh quan',
    descriptionEn: 'Architecture and landscape design',
    accent: '#0891b2',
  },
  {
    abbr: 'TSN',
    name: 'Thaising Nursery',
    tagline: 'Tropical Plants · Thailand',
    description: 'Cung cấp cây nhiệt đới',
    descriptionEn: 'Tropical plant supply from Thailand',
    accent: '#15803d',
  },
  {
    abbr: 'GL',
    name: 'Green Light',
    tagline: 'Landscape Lighting',
    description: 'Chiếu sáng cảnh quan',
    descriptionEn: 'Landscape and architectural lighting',
    accent: '#ca8a04',
  },
  {
    abbr: 'HD',
    name: 'Hung Dat Import-Export',
    tagline: 'Landscape Materials Supply',
    description: 'Cung cấp vật tư cảnh quan',
    descriptionEn: 'Landscape materials import and supply',
    accent: '#b45309',
  },
  {
    abbr: 'DLA',
    name: 'Danang Landscape Association',
    tagline: 'Industry Association',
    description: 'Hiệp hội cảnh quan Đà Nẵng',
    descriptionEn: 'Da Nang Landscape Association',
    accent: '#0f766e',
  },
];
