import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient, Category } from '@prisma/client';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const GOLF = [
  'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=1200&q=80',
  'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=1200&q=80',
  'https://images.unsplash.com/photo-1592919505780-303950717480?w=1200&q=80',
  'https://images.unsplash.com/photo-1567016526105-22da7c13161a?w=1200&q=80',
  'https://images.unsplash.com/photo-1611374243147-44a702c2d44c?w=1200&q=80',
  'https://images.unsplash.com/photo-1600166898405-da9535204843?w=1200&q=80',
  'https://images.unsplash.com/photo-1574015974293-817f0ebebb74?w=1200&q=80',
  'https://images.unsplash.com/photo-1561049501-e1f96bdd98fd?w=1200&q=80',
  'https://images.unsplash.com/photo-1580477667995-2b94f01c9516?w=1200&q=80',
  'https://images.unsplash.com/photo-1542683581-0e1d3a30f06b?w=1200&q=80',
];
const RESORT = [
  'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=80',
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80',
  'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80',
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
  'https://images.unsplash.com/photo-1439130490301-25e322d88054?w=1200&q=80',
  'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&q=80',
  'https://images.unsplash.com/photo-1530092285049-1c42085fd395?w=1200&q=80',
  'https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=1200&q=80',
];
const URBAN = [
  'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=1200&q=80',
  'https://images.unsplash.com/photo-1567942711641-5f0e7d557629?w=1200&q=80',
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&q=80',
  'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80',
  'https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=1200&q=80',
  'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80',
  'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=1200&q=80',
];
const GARDEN = [
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
  'https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=1200&q=80',
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&q=80',
  'https://images.unsplash.com/photo-1504198458649-3128b932f49e?w=1200&q=80',
  'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=1200&q=80',
];
const ARTWORK = [
  'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=1200&q=80',
  'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=1200&q=80',
  'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
  'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=1200&q=80',
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
  'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80',
];

const projects = [
  // GOLF
  { slug: 'golf-brg-danang', title: 'Sân Golf BRG Đà Nẵng', titleEn: 'BRG Da Nang Golf Course', category: Category.GOLF, location: 'Đà Nẵng', client: 'BRG Group', year: '2015', image: GOLF[0].replace('w=1200', 'w=800'), images: [GOLF[0], GOLF[1], GOLF[2], GOLF[3], GOLF[4], GOLF[5]], description: 'Thi công cảnh quan và hệ thống tưới tiêu tự động Rainbird cho 18 lỗ golf BRG tại Đà Nẵng — đạt tiêu chuẩn quốc tế về cỏ và hệ thống tưới.', descriptionEn: 'Landscape construction and Rainbird automatic irrigation for all 18 holes of BRG Da Nang Golf Course — meeting international turf and irrigation standards.' },
  { slug: 'golf-bana-suoi-mo', title: 'Sân Golf Bà Nà – Suối Mơ', titleEn: 'Ba Na Hills – Suoi Mo Golf Course', category: Category.GOLF, location: 'Đà Nẵng', client: 'Sun Group', year: '2017', image: GOLF[1].replace('w=1200', 'w=800'), images: [GOLF[1], GOLF[4], GOLF[7], GOLF[8], GOLF[0], GOLF[9]], description: 'Thi công cảnh quan và hệ thống tưới tiêu cho sân golf Bà Nà – Suối Mơ trong quần thể khu du lịch Bà Nà Hills của Sun Group.', descriptionEn: "Landscape construction and irrigation systems for the Ba Na Hills – Suoi Mo Golf Course within Sun Group's Ba Na Hills resort complex." },
  { slug: 'golf-laguna-lang-co', title: 'Sân Golf Laguna Lăng Cô', titleEn: 'Laguna Lăng Cô Golf Course', category: Category.GOLF, location: 'Thừa Thiên Huế', client: 'Laguna Vietnam', year: '2016', image: GOLF[2].replace('w=1200', 'w=800'), images: [GOLF[2], GOLF[3], GOLF[8], GOLF[1], GOLF[6], GOLF[5]], description: 'Cảnh quan và hệ thống tưới tiêu Rainbird cho sân golf 18 lỗ tại khu nghỉ dưỡng Laguna Lăng Cô — kết hợp giữa cảnh quan tự nhiên và tiêu chuẩn thi đấu quốc tế.', descriptionEn: '18-hole golf course landscape and Rainbird irrigation at Laguna Lăng Cô Resort — blending natural scenery with international tournament standards.' },
  { slug: 'golf-clb-danang', title: 'Câu Lạc Bộ Golf Đà Nẵng (The Dunes)', titleEn: 'Da Nang Golf Club – The Dunes', category: Category.GOLF, location: 'Ngũ Hành Sơn, Đà Nẵng', client: 'VinaCapital', year: '2010', image: GOLF[4].replace('w=1200', 'w=800'), images: [GOLF[4], GOLF[7], GOLF[9], GOLF[0], GOLF[5], GOLF[1]], description: 'Thi công cảnh quan và bảo dưỡng sân golf The Dunes — một trong những sân golf ven biển đẳng cấp nhất miền Trung Việt Nam.', descriptionEn: 'Landscape construction and maintenance for The Dunes golf course — one of the finest beachside golf courses in Central Vietnam.' },
  { slug: 'golf-montgomerie-links', title: 'Sân Golf Montgomerie Links', titleEn: 'Montgomerie Links Golf Course', category: Category.GOLF, location: 'Điện Bàn, Quảng Nam', client: 'VinaCapital / Montgomerie Links Vietnam', year: '2012', image: GOLF[6].replace('w=1200', 'w=800'), images: [GOLF[6], GOLF[3], GOLF[5], GOLF[9], GOLF[2], GOLF[8]], description: 'Thi công cảnh quan và thảm cỏ cho sân golf 18 lỗ Montgomerie Links — thiết kế bởi huyền thoại Colin Montgomerie, nằm giữa đồng bằng ven biển Quảng Nam.', descriptionEn: 'Turf and landscape construction for the 18-hole Montgomerie Links course — designed by legend Colin Montgomerie, set among the coastal plains of Quang Nam.' },
  { slug: 'golf-flc-quy-nhon', title: 'Sân Golf FLC Quy Nhơn', titleEn: 'FLC Quy Nhon Golf Course', category: Category.GOLF, location: 'Quy Nhơn, Bình Định', client: 'FLC Group', year: '2019', image: GOLF[8].replace('w=1200', 'w=800'), images: [GOLF[8], GOLF[0], GOLF[5], GOLF[7], GOLF[3], GOLF[6]], description: 'Cảnh quan và hệ thống tưới tự động cho sân golf ven biển FLC Quy Nhơn — tích hợp cảnh quan biển và thảm cỏ Zoysia đạt tiêu chuẩn thi đấu.', descriptionEn: 'Landscape and automatic irrigation for FLC Quy Nhon beachside golf course — integrating coastal scenery with tournament-grade Zoysia turf.' },
  // RESORT
  { slug: 'laguna-lang-co', title: 'Khu Nghỉ Dưỡng Laguna Lăng Cô', titleEn: 'Laguna Lăng Cô Resort', category: Category.RESORT, location: 'Phú Lộc, Thừa Thiên Huế', area: '280 ha', client: 'Laguna Vietnam', year: '2013', image: RESORT[0].replace('w=1200', 'w=800'), images: [RESORT[0], RESORT[1], RESORT[2], RESORT[3], RESORT[7], GARDEN[1]], description: 'Thiết kế và thi công cảnh quan toàn bộ khu nghỉ dưỡng Laguna Lăng Cô rộng 280 ha — cảnh quan resort, vườn biệt thự và hành lang cây xanh dọc bãi biển.', descriptionEn: 'Full landscape design and construction for the 280-ha Laguna Lăng Cô Resort — resort greenery, villa gardens, and beachfront green corridors.' },
  { slug: 'ocean-villas-danang', title: 'The Ocean Villas Đà Nẵng', titleEn: 'The Ocean Villas Da Nang', category: Category.RESORT, location: 'Ngũ Hành Sơn, Đà Nẵng', area: '150 ha', client: 'VinaCapital', year: '2014', image: RESORT[1].replace('w=1200', 'w=800'), images: [RESORT[1], RESORT[2], RESORT[4], RESORT[3], GARDEN[0], RESORT[8]], description: 'Cảnh quan biệt thự nghỉ dưỡng cao cấp The Ocean Villas — thiết kế vườn riêng từng căn biệt thự, hồ bơi infinity và hành lang cây xanh nội khu.', descriptionEn: 'Premium resort villa landscaping at The Ocean Villas — individual villa gardens, infinity pools, and internal green corridors.' },
  { slug: 'fiore-phan-thiet', title: 'Fiore Healthy Phan Thiết Resort', titleEn: 'Fiore Healthy Phan Thiet Resort', category: Category.RESORT, location: 'Phan Thiết, Bình Thuận', area: '1.8 ha', client: 'Công ty CP Du Lịch Ngọc Sơn', year: '2021', image: RESORT[2].replace('w=1200', 'w=800'), images: [RESORT[2], RESORT[0], GARDEN[1], RESORT[5], RESORT[8], GARDEN[3]], description: 'Thiết kế và thi công cảnh quan khu nghỉ dưỡng Fiore Healthy tại Phan Thiết — cảnh quan nhiệt đới, vườn wellness và không gian nghỉ dưỡng xanh hài hòa.', descriptionEn: 'Landscape design and construction for Fiore Healthy Resort, Phan Thiet — tropical landscaping, wellness garden, and harmonious green resort spaces.' },
  { slug: 'movenpick-novaworld', title: 'Khách Sạn Movenpick Novaworld Phan Thiết', titleEn: 'Movenpick Hotel Novaworld Phan Thiet', category: Category.RESORT, location: 'Phan Thiết', client: 'Delta-Valley Binh Thuan', year: '2022', image: RESORT[3].replace('w=1200', 'w=800'), images: [RESORT[3], RESORT[4], RESORT[7], RESORT[1], RESORT[8], GARDEN[2]], description: 'Cảnh quan khách sạn Movenpick thuộc quần thể Novaworld Phan Thiết — thiết kế và thi công hành lang cây xanh, pool garden và sân vườn sảnh đón.', descriptionEn: 'Landscape works for Movenpick Hotel within the Novaworld Phan Thiet complex — green corridors, pool garden, and lobby forecourt landscaping.' },
  { slug: 'hoiana-maintenance', title: 'HOIANA – Bảo Dưỡng Cảnh Quan', titleEn: 'HOIANA Resort Landscape Maintenance', category: Category.RESORT, location: 'Hội An, Quảng Nam', client: 'HOIANA', year: '2021', image: RESORT[5].replace('w=1200', 'w=800'), images: [RESORT[5], RESORT[6], RESORT[7], RESORT[0], RESORT[8], GARDEN[4]], description: 'Dịch vụ bảo dưỡng cảnh quan dài hạn cho khu nghỉ dưỡng HOIANA tại Hội An — duy trì chất lượng cây xanh, thảm cỏ và hệ sinh thái cảnh quan toàn khu.', descriptionEn: "Long-term landscape maintenance services for HOIANA Resort, Hoi An — maintaining greenery quality, turf, and the resort's complete landscape ecosystem." },
  { slug: 'intercontinental-danang', title: 'InterContinental Đà Nẵng Sun Peninsula', titleEn: 'InterContinental Da Nang Sun Peninsula', category: Category.RESORT, location: 'Sơn Trà, Đà Nẵng', area: '39 ha', client: 'Sun Group', year: '2014', image: RESORT[6].replace('w=1200', 'w=800'), images: [RESORT[6], RESORT[0], RESORT[4], GARDEN[0], RESORT[2], RESORT[7]], description: 'Thi công cảnh quan nhiệt đới cho khu nghỉ dưỡng 5 sao InterContinental trên bán đảo Sơn Trà — cảnh quan hoà nhập với rừng nhiệt đới tự nhiên.', descriptionEn: 'Tropical landscape construction for the 5-star InterContinental resort on Son Tra Peninsula — landscaping integrated with the natural tropical forest.' },
  { slug: 'fusion-resort-cam-ranh', title: 'Fusion Resort Cam Ranh', titleEn: 'Fusion Resort Cam Ranh', category: Category.RESORT, location: 'Cam Ranh, Khánh Hòa', client: 'Fusion Resorts', year: '2018', image: RESORT[8].replace('w=1200', 'w=800'), images: [RESORT[8], RESORT[1], GARDEN[1], RESORT[5], RESORT[3], GARDEN[5]], description: 'Thiết kế và thi công cảnh quan resort all-spa Fusion tại Cam Ranh — vườn thiền, đường dạo ven biển và không gian cây xanh hài hòa với kiến trúc.', descriptionEn: 'Landscape design and construction for Fusion Resort Cam Ranh — zen garden, beachside walkways, and greenery harmonising with the architecture.' },
  // URBAN
  { slug: 'hue-traffic-landscape', title: 'Cảnh Quan Đường Giao Thông TP Huế', titleEn: 'Hue City Traffic Road Landscape', category: Category.URBAN, location: 'TP Huế, Thừa Thiên Huế', client: 'Ban Môi Trường & Đô Thị Huế', year: '2015', image: URBAN[0].replace('w=1200', 'w=800'), images: [URBAN[0], URBAN[1], URBAN[2], URBAN[3], URBAN[4], URBAN[5]], description: 'Cảnh quan hoá các tuyến đường giao thông trọng điểm của thành phố Huế — trồng cây, thảm cỏ, hoa và thiết kế dải phân cách đô thị xanh.', descriptionEn: 'Landscaping of key traffic roads in Hue City — tree planting, turf, flowers, and green median strip design across major urban corridors.' },
  { slug: 'ngu-ha-river-hue', title: 'Cải Tạo Sông Ngự Hà TP Huế', titleEn: 'Ngu Ha River Renovation, Hue City', category: Category.URBAN, location: 'TP Huế', client: 'Ban Môi Trường & Đô Thị Huế', year: '2018', image: URBAN[1].replace('w=1200', 'w=800'), images: [URBAN[1], URBAN[0], URBAN[5], URBAN[6], URBAN[7], URBAN[2]], description: 'Cải tạo và cảnh quan hoá dọc bờ sông Ngự Hà — tạo hành lang xanh đô thị, lối đi bộ ven sông và không gian công cộng mới cho người dân Huế.', descriptionEn: 'Renovation and landscaping along the Ngu Ha River bank — creating an urban green corridor, riverside walkways, and new public spaces for Hue residents.' },
  { slug: 'manor-crown-hue', title: 'The Manor Crown Huế', titleEn: 'The Manor Crown Hue', category: Category.URBAN, location: 'Huế', client: 'BIM Group', year: '2019', image: URBAN[2].replace('w=1200', 'w=800'), images: [URBAN[2], URBAN[3], URBAN[4], URBAN[5], GARDEN[1], URBAN[6]], description: 'Thiết kế và thi công cảnh quan khu đô thị cao cấp The Manor Crown tại Huế — cảnh quan nội khu, vườn công cộng và cây xanh đường nội bộ.', descriptionEn: 'Landscape design and construction for The Manor Crown premium urban development in Hue — internal landscape, public gardens, and street trees.' },
  { slug: 'vinpearl-phu-quoc-urban', title: 'Khu Đô Thị Vinpearl Phú Quốc', titleEn: 'Vinpearl Phu Quoc Urban Development', category: Category.URBAN, location: 'Phú Quốc, Kiên Giang', client: 'Vingroup', year: '2020', image: URBAN[4].replace('w=1200', 'w=800'), images: [URBAN[4], URBAN[6], URBAN[7], URBAN[0], GARDEN[2], URBAN[3]], description: 'Cảnh quan đô thị cho khu phức hợp Vinpearl tại Phú Quốc — trồng cây đường phố, công viên nội khu và hành lang xanh kết nối các tiện ích.', descriptionEn: 'Urban landscaping for the Vinpearl complex in Phu Quoc — street trees, internal parks, and green corridors connecting amenities.' },
  // URBAN (mapped from Construction)
  { slug: 'casamia-hoi-an', title: 'Khu Đô Thị Casamia Hội An', titleEn: 'Casamia Hoi An Urban Area', category: Category.URBAN, location: 'Cẩm Thanh, Hội An, Quảng Nam', area: '6.4 ha', client: 'Đạt Phương Corp', year: '2020', image: URBAN[3].replace('w=1200', 'w=800'), images: [URBAN[3], URBAN[4], GARDEN[1], GARDEN[0], URBAN[1], URBAN[7]], description: 'Thi công cảnh quan và hạ tầng xanh cho khu đô thị Casamia tại Hội An — cảnh quan đường nội khu, công viên trung tâm và hành lang cây xanh 6.4 ha.', descriptionEn: 'Landscape and green infrastructure construction for the Casamia urban development in Hoi An — internal road landscaping, central park, and 6.4-ha green corridors.' },
  { slug: 'seava-ho-tram', title: 'Seava Hồ Tràm Strip', titleEn: 'Seava Ho Tram Strip', category: Category.URBAN, location: 'Hồ Tràm, Bà Rịa - Vũng Tàu', client: 'Seava', year: '2021', image: GARDEN[3].replace('w=1200', 'w=800'), images: [GARDEN[3], RESORT[4], GARDEN[0], URBAN[5], RESORT[7], GARDEN[5]], description: 'Thi công cảnh quan và cây xanh cho tổ hợp Seava tại Hồ Tràm — cảnh quan ven biển, hệ thống tưới nhỏ giọt và vườn cây nhiệt đới đặc trưng.', descriptionEn: 'Landscape and planting works for the Seava Ho Tram complex — coastal landscaping, drip irrigation, and signature tropical garden.' },
  { slug: 'sunbay-park-ninh-thuan', title: 'Sun Bay Park Ninh Thuận', titleEn: 'Sun Bay Park Ninh Thuan', category: Category.URBAN, location: 'Ninh Thuận', client: 'Sun Group', year: '2023', image: URBAN[6].replace('w=1200', 'w=800'), images: [URBAN[6], URBAN[7], GARDEN[4], GARDEN[1], RESORT[6], URBAN[4]], description: 'Thi công cảnh quan khu nghỉ dưỡng và công viên Sun Bay tại Ninh Thuận — hệ thống tưới thông minh, vườn xương rồng và cảnh quan sa mạc nhiệt đới.', descriptionEn: 'Landscape construction for Sun Bay Park resort in Ninh Thuan — smart irrigation, cactus garden, and tropical desert landscaping.' },
  // ARTWORK
  { slug: 'cau-dat-farm-dalat', title: 'Cầu Đất Farm – Đà Lạt', titleEn: 'Cau Dat Farm – Da Lat', category: Category.ARTWORK, location: 'Trạm Hành, Đà Lạt, Lâm Đồng', area: '230 ha', client: 'Novaland / Cau Dat Tea JSC', year: '2022', image: GARDEN[0].replace('w=1200', 'w=800'), images: [GARDEN[0], GARDEN[2], GARDEN[3], GARDEN[4], GARDEN[5], GARDEN[6]], description: 'Thi công cảnh quan và artwork cho khu nông trại sinh thái Cầu Đất rộng 230 ha tại Đà Lạt — công trình nghệ thuật iconic hoà quyện với địa hình đồi chè.', descriptionEn: 'Landscape and artwork construction for the 230-ha Cau Dat eco-farm in Da Lat — iconic art installations blending with the tea-plantation terrain.' },
  { slug: 'tropicana-novaworld', title: 'The Tropicana – Novaworld Hồ Tràm', titleEn: 'The Tropicana – Novaworld Ho Tram', category: Category.ARTWORK, location: 'Hồ Tràm, Bà Rịa - Vũng Tàu', client: 'Novaland', year: '2022', image: ARTWORK[0].replace('w=1200', 'w=800'), images: [ARTWORK[0], ARTWORK[1], ARTWORK[2], ARTWORK[3], ARTWORK[4], ARTWORK[5]], description: 'Thi công cảnh quan và công trình Artwork biểu tượng cho khu The Tropicana tại Novaworld Hồ Tràm — tạo dấu ấn nhận diện độc đáo cho dự án nghỉ dưỡng ven biển.', descriptionEn: 'Landscape and iconic Artwork construction for The Tropicana at Novaworld Ho Tram — creating a unique landmark identity for the beachside resort development.' },
  { slug: 'sunworld-bana-hills', title: 'Sun World Bà Nà Hills – Artwork Cảnh Quan', titleEn: 'Sun World Ba Na Hills – Landscape Artwork', category: Category.ARTWORK, location: 'Đà Nẵng', client: 'Sun Group', year: '2020', image: ARTWORK[2].replace('w=1200', 'w=800'), images: [ARTWORK[2], ARTWORK[4], ARTWORK[1], GARDEN[2], ARTWORK[5], ARTWORK[3]], description: 'Thi công các hạng mục Artwork và cảnh quan đặc biệt tại Sun World Bà Nà Hills — tạo điểm nhấn nghệ thuật iconic trong không gian giải trí độc đáo.', descriptionEn: 'Construction of Artwork and special landscape features at Sun World Ba Na Hills — creating iconic artistic highlights in a unique entertainment landscape.' },
  { slug: 'hoiana-artwork', title: 'HOIANA – Artwork & Cảnh Quan Đặc Biệt', titleEn: 'HOIANA – Artwork & Feature Landscape', category: Category.ARTWORK, location: 'Hội An, Quảng Nam', client: 'HOIANA', year: '2022', image: ARTWORK[4].replace('w=1200', 'w=800'), images: [ARTWORK[4], ARTWORK[0], ARTWORK[3], RESORT[5], ARTWORK[2], GARDEN[3]], description: 'Thiết kế và thi công các công trình Artwork cảnh quan đặc biệt cho khu nghỉ dưỡng HOIANA — kết hợp nghệ thuật đương đại và văn hóa địa phương Hội An.', descriptionEn: 'Design and construction of feature Artwork for HOIANA Resort — blending contemporary art with the local culture and heritage of Hoi An.' },
];

const heroSlides = [
  { url: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1920&q=90', labelVi: 'Cảnh quan nghỉ dưỡng', labelEn: 'Resort Landscape', order: 0 },
  { url: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=1920&q=90', labelVi: 'Sân Golf', labelEn: 'Golf Course', order: 1 },
  { url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1920&q=90', labelVi: 'Vườn Biệt Thự', labelEn: 'Villa Garden', order: 2 },
  { url: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=1920&q=90', labelVi: 'Công Viên Đô Thị', labelEn: 'Urban Park', order: 3 },
  { url: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1920&q=90', labelVi: 'Cảnh quan Sinh Thái', labelEn: 'Eco Landscape', order: 4 },
];

const services = [
  { number: '01', titleVi: 'Tư vấn & Quản lý cảnh quan', titleEn: 'Landscape Consulting & Management', descVi: 'Quy trình thiết kế, sáng tạo, tư vấn, thi công, bảo hành và bảo dưỡng toàn diện.', descEn: 'Full-cycle process: design, consulting, construction, warranty and maintenance.', tag: 'Consulting', iconSvg: 'M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25z', order: 0 },
  { number: '02', titleVi: 'Thiết kế & Thi công cảnh quan', titleEn: 'Landscape Design & Construction', descVi: 'Sản phẩm theo yêu cầu dựa trên kiến thức và kinh nghiệm thực tiễn trong lĩnh vực cảnh quan.', descEn: 'Tailored outputs built on deep practical knowledge and field experience in landscaping.', tag: 'Design · Build', iconSvg: 'M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909M3 21h18M3.75 3h16.5M4.5 3v18M19.5 3v18', order: 1 },
  { number: '03', titleVi: 'Thiết kế & Thi công Artwork', titleEn: 'Artwork Design & Construction', descVi: 'Mẫu thiết kế nghệ thuật tùy chỉnh phù hợp với quy mô và đặc thù của từng công trình.', descEn: 'Custom artistic designs tailored to the scale and character of each project.', tag: 'Art · Identity', iconSvg: 'M9.53 16.122a3 3 0 00-5.78 1.128 2.25 2.25 0 01-2.4 2.245 4.5 4.5 0 008.4-2.245c0-.399-.078-.78-.22-1.128zm0 0a15.998 15.998 0 003.388-1.62m-5.043-.025a15.994 15.994 0 011.622-3.395m3.42 3.42a15.995 15.995 0 004.764-4.648l3.876-5.814a1.151 1.151 0 00-1.597-1.597L14.146 6.32a15.996 15.996 0 00-4.649 4.763m3.42 3.42a6.776 6.776 0 00-3.42-3.42', order: 2 },
  { number: '04', titleVi: 'Cung ứng lao động', titleEn: 'Labour Supply', descVi: 'Cung ứng nhân lực chuyên nghiệp cho thi công và bảo dưỡng các hạng mục cảnh quan.', descEn: 'Skilled workforce supply for landscape construction and maintenance projects.', tag: 'Workforce', iconSvg: 'M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z', order: 3 },
  { number: '05', titleVi: 'Cung ứng vật liệu cảnh quan', titleEn: 'Landscape Materials Supply', descVi: 'Cho thuê và cung cấp cây xanh, thảm cỏ, hệ thống tưới và vật liệu cảnh quan đa dạng.', descEn: 'Supply and rental of trees, turf, irrigation systems and diverse landscape materials.', tag: 'Materials', iconSvg: 'M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5M10 11.25h4M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z', order: 4 },
  { number: '06', titleVi: 'Dịch vụ bảo dưỡng', titleEn: 'Maintenance Services', descVi: 'Bảo dưỡng định kỳ cây xanh và công trình cảnh quan, đảm bảo không gian luôn xanh đẹp.', descEn: 'Regular maintenance of greenery and landscape works to keep spaces vibrant year-round.', tag: 'Maintenance', iconSvg: 'M11.42 15.17L17.25 21A2.652 2.652 0 0021 17.25l-5.877-5.877M11.42 15.17l2.496-3.03c.317-.384.74-.626 1.208-.766M11.42 15.17l-4.655 5.653a2.548 2.548 0 11-3.586-3.586l6.837-5.63m5.108-.233c.55-.164 1.163-.188 1.743-.14a4.5 4.5 0 004.486-6.336l-3.276 3.277a3.004 3.004 0 01-2.25-2.25l3.276-3.276a4.5 4.5 0 00-6.336 4.486c.091 1.076-.071 2.264-.904 2.95l-.102.085m-1.745 1.437L5.909 7.5H4.5L2.25 3.75l1.5-1.5L7.5 4.5v1.409l4.26 4.26m-1.745 1.437l1.745-1.437m6.615 8.206L15.75 15.75M4.867 19.125h.008v.008h-.008v-.008z', order: 5 },
];

const timelineItems = [
  { year: '2007–2008', title: 'Khởi nghiệp', titleEn: 'Founding', description: 'Khởi đầu bằng nhập khẩu và phân phối hoa, cung ứng lao động cảnh quan mềm (cây, hoa, thảm cỏ).', descriptionEn: 'Started with flower import/distribution and soft landscape labour supply — trees, flowers, and turf.', order: 0 },
  { year: '2009–2013', title: 'Hình thành và phát triển', titleEn: 'Formation & Growth', description: 'Xây dựng đội ngũ nhân lực, đầu tư vườn ươm, thiết lập quan hệ đối tác với các tập đoàn bất động sản lớn.', descriptionEn: 'Built a skilled workforce, invested in a plant nursery, and established partnerships with major real estate groups.', order: 1 },
  { year: '2014–2018', title: 'Mở rộng dịch vụ', titleEn: 'Service Expansion', description: 'Mở rộng sang hạ tầng, cảnh quan cứng, hệ thống tưới tiêu. Khai trương văn phòng Huế, phát triển thị trường miền Trung.', descriptionEn: 'Expanded into infrastructure, hardscape, and irrigation systems. Opened Hue office and grew the Central Vietnam market.', order: 2 },
  { year: '2018–2022', title: 'Nhà thầu chính đa lĩnh vực', titleEn: 'Full-Service Main Contractor', description: 'Trở thành tổng thầu thiết kế + thi công. Mở rộng sang MEP, nghệ thuật công trình và hợp tác ASEAN.', descriptionEn: 'Became main contractor for full design+build. Expanded into MEP, artwork installation, and ASEAN cooperation.', order: 3 },
  { year: '2023–nay', title: 'Tăng trưởng bền vững', titleEn: 'Sustainable Growth', description: 'Tái cơ cấu tổ chức, áp dụng tiêu chuẩn ISO, đầu tư hệ thống CNTT và tăng cường đối tác golf–cảnh quan.', descriptionEn: 'Restructured the organisation, applied ISO standards, invested in IT systems, and strengthened golf-landscape partnerships.', order: 4 },
];

const partners = [
  { name: 'VinaCapital', sector: 'Đầu tư & Bất động sản', sectorEn: 'Investment & Real Estate', descVi: 'Tập đoàn đầu tư và bất động sản hàng đầu Việt Nam, chủ đầu tư nhiều khu nghỉ dưỡng và khu đô thị cao cấp.', descEn: 'Leading investment and real estate group in Vietnam, developer of many premium resorts and urban areas.', founded: 2003, hq: 'TP. Hồ Chí Minh, Việt Nam', statLabelVi: 'Tổng tài sản quản lý', statLabelEn: 'Assets under management', statValue: '~4 tỷ USD', projectsVi: ['Danang Golf Club – cảnh quan sân golf 36 lỗ', 'VinaCapital Resort Hội An – cây xanh & tiểu cảnh', 'Sky Villas Đà Nẵng – cảnh quan khuôn viên'], projectsEn: ['Danang Golf Club – 36-hole golf landscape', 'VinaCapital Resort Hoi An – planting & softscape', 'Sky Villas Da Nang – estate landscaping'], highlightVi: 'Chủ đầu tư lớn nhất tại Đà Nẵng, hợp tác với FAM từ 2010.', highlightEn: 'Largest investor in Da Nang, partnering with FAM since 2010.', order: 0 },
  { name: 'Novaland', sector: 'Phát triển Bất động sản', sectorEn: 'Real Estate Developer', descVi: 'Tập đoàn phát triển bất động sản lớn tại Việt Nam với nhiều dự án nghỉ dưỡng và đô thị trên toàn quốc.', descEn: 'One of the largest real estate developers in Vietnam with resort and urban projects nationwide.', founded: 1992, hq: 'TP. Hồ Chí Minh, Việt Nam', statLabelVi: 'Dự án phát triển', statLabelEn: 'Development projects', statValue: '50+ dự án', projectsVi: ['NovaWorld Hồ Tràm – cảnh quan khu đô thị biển', 'Aqua City Đồng Nai – mảng xanh & công viên nội khu', 'NovaBeach Cam Ranh – softscape resort'], projectsEn: ['NovaWorld Ho Tram – coastal urban landscape', 'Aqua City Dong Nai – greenery & internal parks', 'NovaBeach Cam Ranh – resort softscape'], highlightVi: 'Một trong những chủ đầu tư bất động sản nghỉ dưỡng lớn nhất Việt Nam.', highlightEn: 'One of the largest resort real estate developers in Vietnam.', order: 1 },
  { name: 'BRG Group', sector: 'Tập đoàn Đa ngành', sectorEn: 'Diversified Conglomerate', descVi: 'Tập đoàn BRG sở hữu nhiều sân golf và khu nghỉ dưỡng cao cấp, là đối tác chiến lược lâu năm của FAM.', descEn: 'BRG Group owns multiple premium golf courses and resorts, a long-term strategic partner of FAM.', founded: 1993, hq: 'Hà Nội, Việt Nam', statLabelVi: 'Sân golf sở hữu', statLabelEn: 'Golf courses owned', statValue: '7 sân golf', projectsVi: ['Đảo Vua Golf – tái cảnh quan 18 lỗ', 'BRG Da Nang Golf Resort – cảnh quan sân & khuôn viên', 'Hilton Hanoi Opera – cây xanh & sân vườn khách sạn'], projectsEn: ['Kings Island Golf – 18-hole landscape renovation', 'BRG Da Nang Golf Resort – course & estate landscape', 'Hilton Hanoi Opera – hotel green & garden works'], highlightVi: 'Đối tác golf chiến lược hàng đầu của FAM Landscape tại miền Bắc.', highlightEn: "FAM Landscape's leading strategic golf partner in Northern Vietnam.", order: 2 },
  { name: 'Laguna Lăng Cô', sector: 'Khu nghỉ dưỡng Quốc tế', sectorEn: 'International Resort', descVi: 'Khu nghỉ dưỡng đẳng cấp quốc tế tại Lăng Cô, Thừa Thiên Huế. FAM đã thi công cảnh quan sân golf và khuôn viên resort.', descEn: 'World-class resort in Lang Co, Thua Thien Hue. FAM executed landscape and golf course works.', founded: 2013, hq: 'Lăng Cô, Thừa Thiên Huế, Việt Nam', statLabelVi: 'Diện tích khu nghỉ dưỡng', statLabelEn: 'Resort area', statValue: '280 ha', projectsVi: ['Sân golf 18 lỗ Laguna – cảnh quan toàn bộ', 'Biệt thự ven biển – cây xanh & hồ cảnh', 'Khu villa Banyan Tree – tiểu cảnh nhiệt đới'], projectsEn: ['Laguna 18-hole golf – full landscape works', 'Beachfront villas – planting & water features', 'Banyan Tree villa zone – tropical softscape'], highlightVi: 'Dự án cảnh quan sân golf quốc tế đầu tiên FAM thực hiện tại miền Trung.', highlightEn: 'First international golf landscape project FAM completed in Central Vietnam.', order: 3 },
  { name: 'Sun Group', sector: 'Du lịch & Giải trí', sectorEn: 'Tourism & Entertainment', descVi: 'Tập đoàn Sun Group sở hữu Bà Nà Hills, Phú Quốc Discovery và nhiều điểm đến nổi tiếng trên toàn quốc.', descEn: 'Sun Group owns Ba Na Hills, Phu Quoc Discovery, and many landmark destinations across Vietnam.', founded: 2007, hq: 'Hà Nội, Việt Nam', statLabelVi: 'Điểm đến biểu tượng', statLabelEn: 'Iconic destinations', statValue: '20+ dự án', projectsVi: ['Bà Nà Hills – cảnh quan vườn hoa & thảm cỏ', 'Sun World Phú Quốc – cây xanh khu vui chơi', 'Premier Village Đà Nẵng – sân vườn biệt thự biển'], projectsEn: ['Ba Na Hills – flower garden & lawn landscape', 'Sun World Phu Quoc – theme park greenery', 'Premier Village Da Nang – beachfront villa gardens'], highlightVi: 'Chủ đầu tư của Cầu Vàng nổi tiếng thế giới tại Bà Nà Hills.', highlightEn: 'Developer of the world-famous Golden Bridge at Ba Na Hills.', order: 4 },
  { name: 'Hung Thinh Corp', sector: 'Bất động sản', sectorEn: 'Real Estate', descVi: 'Tập đoàn Hưng Thịnh – nhà phát triển bất động sản lớn tại TP.HCM và các tỉnh thành miền Nam.', descEn: 'Hung Thinh Corporation – major real estate developer in Ho Chi Minh City and southern provinces.', founded: 2002, hq: 'TP. Hồ Chí Minh, Việt Nam', statLabelVi: 'Dự án đã bàn giao', statLabelEn: 'Delivered projects', statValue: '60+ dự án', projectsVi: ['MerryLand Quy Nhơn – cảnh quan resort & marina', 'The Maris Vũng Tàu – sân vườn căn hộ cao tầng', 'Charm Resort Hồ Tràm – softscape khu nghỉ dưỡng'], projectsEn: ['MerryLand Quy Nhon – resort & marina landscape', 'The Maris Vung Tau – high-rise apartment gardens', 'Charm Resort Ho Tram – resort softscape'], highlightVi: 'Một trong top 5 nhà phát triển bất động sản lớn nhất miền Nam.', highlightEn: 'One of the top 5 largest real estate developers in Southern Vietnam.', order: 5 },
  { name: 'Fusion Resort', sector: 'Hospitality', sectorEn: 'Hospitality', descVi: 'Chuỗi resort cao cấp với triết lý "all-spa-inclusive" độc đáo, hoạt động tại Đà Nẵng, Cam Ranh và Phú Quốc.', descEn: 'Premium resort chain with a unique "all-spa-inclusive" philosophy, operating in Da Nang, Cam Ranh and Phu Quoc.', founded: 2008, hq: 'Đà Nẵng, Việt Nam', statLabelVi: 'Resort trong chuỗi', statLabelEn: 'Resorts in chain', statValue: '8 resort', projectsVi: ['Fusion Maia Đà Nẵng – cảnh quan nhiệt đới & hồ bơi', 'Fusion Resort Cam Ranh – vườn nhiệt đới ven biển', 'Fusion Suites Sài Gòn – sân vườn tầng mái'], projectsEn: ['Fusion Maia Da Nang – tropical & pool landscape', 'Fusion Resort Cam Ranh – beachside tropical garden', 'Fusion Suites Saigon – rooftop garden'], highlightVi: 'Thương hiệu resort Việt đầu tiên áp dụng mô hình "all-spa-inclusive".', highlightEn: 'First Vietnamese resort brand to apply the "all-spa-inclusive" model.', order: 6 },
  { name: 'HOIANA', sector: 'Nghỉ dưỡng & Casino', sectorEn: 'Resort & Casino', descVi: 'Khu nghỉ dưỡng tích hợp HOIANA tại Quảng Nam – điểm đến sang trọng bậc nhất miền Trung Việt Nam.', descEn: 'HOIANA integrated resort complex in Quang Nam – the most luxurious destination in Central Vietnam.', founded: 2019, hq: 'Quảng Nam, Việt Nam', statLabelVi: 'Tổng vốn đầu tư', statLabelEn: 'Total investment', statValue: '4 tỷ USD', projectsVi: ['HOIANA Sands Golf – cảnh quan sân golf ven biển', 'Hoiana Hotel & Suites – cây xanh & hồ cảnh nội khu', 'Rosewood Hoi An – tiểu cảnh sang trọng & bờ biển'], projectsEn: ['HOIANA Sands Golf – beachside golf landscape', 'Hoiana Hotel & Suites – internal planting & water features', 'Rosewood Hoi An – luxury softscape & beachfront'], highlightVi: 'Khu tích hợp casino – resort duy nhất tại miền Trung, vốn đầu tư 4 tỷ USD.', highlightEn: 'The only integrated casino-resort in Central Vietnam, with $4 billion investment.', order: 7 },
  { name: 'Radisson', sector: 'Khách sạn Quốc tế', sectorEn: 'International Hotel', descVi: 'Tập đoàn khách sạn quốc tế Radisson với nhiều thương hiệu cao cấp hoạt động tại Việt Nam.', descEn: 'International hotel group Radisson with multiple premium brands operating in Vietnam.', founded: 1960, hq: 'Brussels, Bỉ', statLabelVi: 'Khách sạn toàn cầu', statLabelEn: 'Global hotels', statValue: '1,700+ khách sạn', projectsVi: ['Radisson Blu Đà Nẵng – sân vườn & hồ bơi ngoài trời', 'Radisson Resort Phú Quốc – tiểu cảnh nhiệt đới', 'Park Inn Đà Nẵng – cảnh quan sân thượng & lối vào'], projectsEn: ['Radisson Blu Da Nang – outdoor garden & pool landscape', 'Radisson Resort Phu Quoc – tropical softscape', 'Park Inn Da Nang – rooftop & entrance landscape'], highlightVi: 'Hiện diện tại 120+ quốc gia, FAM là đối tác cảnh quan tại Việt Nam.', highlightEn: 'Present in 120+ countries; FAM is their landscape partner in Vietnam.', order: 8 },
  { name: 'Minor International', sector: 'Hospitality & F&B', sectorEn: 'Hospitality & F&B', descVi: 'Tập đoàn Minor International – chuỗi khách sạn và nhà hàng cao cấp tại Việt Nam và châu Á.', descEn: 'Minor International – premium hotel and restaurant chain across Vietnam and Asia.', founded: 1978, hq: 'Bangkok, Thái Lan', statLabelVi: 'Khách sạn tại châu Á', statLabelEn: 'Hotels in Asia', statValue: '530+ khách sạn', projectsVi: ['Anantara Hội An – vườn nhiệt đới & hành lang cây xanh', 'NH Collection Đà Nẵng – cảnh quan mặt tiền & sảnh', 'Avani+ Quy Nhơn Resort – bãi biển & sân vườn biệt thự'], projectsEn: ['Anantara Hoi An – tropical garden & green corridors', 'NH Collection Da Nang – façade & lobby landscape', 'Avani+ Quy Nhon Resort – beach & villa garden works'], highlightVi: 'Vận hành thương hiệu Anantara và NH Collection tại nhiều tỉnh thành Việt Nam.', highlightEn: 'Operates Anantara and NH Collection brands across multiple Vietnamese provinces.', order: 9 },
  { name: 'Obayashi Vietnam', sector: 'Xây dựng Quốc tế', sectorEn: 'International Construction', descVi: 'Công ty con của Tập đoàn Obayashi Nhật Bản – nhà thầu xây dựng uy tín hàng đầu tại Việt Nam.', descEn: "Subsidiary of Japan's Obayashi Corporation – one of the most reputable construction contractors in Vietnam.", founded: 1892, hq: 'Osaka, Nhật Bản', statLabelVi: 'Doanh thu tập đoàn mẹ', statLabelEn: 'Parent group revenue', statValue: '~18 tỷ USD/năm', projectsVi: ['Khu đô thị Phú Mỹ Hưng – cảnh quan đại lộ & công viên', 'Keangnam Landmark Hà Nội – sân vườn tòa nhà', 'Dự án hạ tầng metro TP.HCM – cây xanh đô thị'], projectsEn: ['Phu My Hung Township – boulevard & park landscape', 'Keangnam Landmark Hanoi – building green works', 'HCMC Metro Infrastructure – urban greenery'], highlightVi: 'Tập đoàn xây dựng lớn thứ 4 Nhật Bản, hợp tác cảnh quan với FAM tại các công trình quy mô lớn.', highlightEn: "Japan's 4th largest construction group, collaborating with FAM on large-scale landscape works.", order: 10 },
  { name: 'Vicoland Group', sector: 'Bất động sản', sectorEn: 'Real Estate', descVi: 'Tập đoàn Vicoland phát triển nhiều dự án khu đô thị và nhà ở tại miền Trung Việt Nam.', descEn: 'Vicoland Group develops urban and residential projects in Central Vietnam.', founded: 2007, hq: 'Đà Nẵng, Việt Nam', statLabelVi: 'Dự án tại miền Trung', statLabelEn: 'Projects in Central Vietnam', statValue: '15+ dự án', projectsVi: ['The Ori Garden Đà Nẵng – cảnh quan khu dân cư', 'Vicoland Riverside – cây xanh & hành lang sông', 'Marina Complex Đà Nẵng – tiểu cảnh khuôn viên'], projectsEn: ['The Ori Garden Da Nang – residential landscape', 'Vicoland Riverside – greenery & riverside corridor', 'Marina Complex Da Nang – campus softscape'], highlightVi: 'Một trong những nhà phát triển bất động sản lâu đời nhất tại Đà Nẵng.', highlightEn: 'One of the longest-standing real estate developers in Da Nang.', order: 11 },
  { name: 'Dat Phuong', sector: 'Bất động sản', sectorEn: 'Real Estate', descVi: 'Công ty Cổ phần Đất Phương – nhà phát triển bất động sản uy tín tại Đà Nẵng và khu vực miền Trung.', descEn: 'Dat Phuong JSC – a reputable real estate developer in Da Nang and the Central region.', founded: 2005, hq: 'Đà Nẵng, Việt Nam', statLabelVi: 'Diện tích đất phát triển', statLabelEn: 'Land area developed', statValue: '500+ ha', projectsVi: ['Khu đô thị Phú Mỹ An – cảnh quan đường nội khu', 'Đất Phương Liên Chiểu – cây xanh khu dân cư', 'Shophouse Đà Nẵng – tiểu cảnh mặt tiền'], projectsEn: ['Phu My An Township – internal road landscape', 'Dat Phuong Lien Chieu – residential greenery', 'Da Nang Shophouses – facade softscape'], highlightVi: 'Đối tác bất động sản nội địa lâu năm của FAM tại khu vực Đà Nẵng.', highlightEn: 'Long-term local real estate partner of FAM in the Da Nang area.', order: 12 },
  { name: 'TTC Land', sector: 'Bất động sản', sectorEn: 'Real Estate', descVi: 'TTC Land (Thành Thành Công) – nhà phát triển bất động sản và khu du lịch sinh thái trên cả nước.', descEn: 'TTC Land (Thanh Thanh Cong) – real estate and eco-tourism developer nationwide.', founded: 1979, hq: 'TP. Hồ Chí Minh, Việt Nam', statLabelVi: 'Tập đoàn thành viên', statLabelEn: 'Member companies', statValue: '30+ công ty', projectsVi: ['TTC Sugar Resort Phan Thiết – cảnh quan eco-resort', 'Khu đô thị TTC Long An – cây xanh & mặt nước', 'Alma Resort Cam Ranh – softscape khuôn viên resort'], projectsEn: ['TTC Sugar Resort Phan Thiet – eco-resort landscape', 'TTC Long An Township – greenery & water features', 'Alma Resort Cam Ranh – resort campus softscape'], highlightVi: 'Sở hữu chuỗi resort sinh thái đường mía độc đáo tại Việt Nam.', highlightEn: 'Owns a unique sugarcane eco-resort chain across Vietnam.', order: 13 },
  { name: 'Sacomreal', sector: 'Bất động sản', sectorEn: 'Real Estate', descVi: 'Sacomreal (SCR) – công ty bất động sản thuộc hệ sinh thái Sacombank, phát triển nhiều dự án căn hộ và resort.', descEn: 'Sacomreal (SCR) – real estate company in the Sacombank ecosystem, developing apartments and resort projects.', founded: 2002, hq: 'TP. Hồ Chí Minh, Việt Nam', statLabelVi: 'Vốn điều lệ', statLabelEn: 'Charter capital', statValue: '1,800 tỷ VNĐ', projectsVi: ['Khu nghỉ dưỡng Phan Thiết – cảnh quan bãi biển', 'Chung cư SCR TP.HCM – sân vườn & hồ bơi nội khu', 'Sacomreal Garden Hill – tiểu cảnh khu dân cư'], projectsEn: ['Phan Thiet Resort – beachfront landscape', 'SCR Apartments HCMC – internal garden & pool works', 'Sacomreal Garden Hill – residential softscape'], highlightVi: 'Niêm yết trên HOSE, thành viên hệ sinh thái tài chính Sacombank.', highlightEn: 'Listed on HOSE, member of the Sacombank financial ecosystem.', order: 14 },
  { name: 'Six Senses', sector: 'Luxury Resort', sectorEn: 'Luxury Resort', descVi: 'Thương hiệu resort siêu sang Six Senses với triết lý du lịch bền vững và trải nghiệm thiên nhiên độc đáo.', descEn: 'Ultra-luxury resort brand Six Senses with a sustainable tourism philosophy and unique nature experiences.', founded: 1995, hq: 'Bangkok, Thái Lan (thuộc IHG)', statLabelVi: 'Resort trên toàn cầu', statLabelEn: 'Resorts worldwide', statValue: '22 resort', projectsVi: ['Six Senses Ninh Vân Bay – cảnh quan vách đá & bãi biển', 'Six Senses Côn Đảo – vườn nhiệt đới & hồ cảnh', 'Six Senses Cần Thơ – tiểu cảnh sông nước miền Tây'], projectsEn: ['Six Senses Ninh Van Bay – cliff & beachfront landscape', 'Six Senses Con Dao – tropical garden & water features', 'Six Senses Can Tho – Mekong-inspired water landscape'], highlightVi: 'Thương hiệu resort hạng nhất thế giới, FAM cung cấp cây nhiệt đới đặc chủng.', highlightEn: 'World-class resort brand; FAM supplies specialty tropical plants for their properties.', order: 15 },
  { name: 'Marriott', sector: 'Khách sạn Quốc tế', sectorEn: 'International Hotel', descVi: 'Tập đoàn khách sạn Marriott International với hơn 30 thương hiệu khách sạn và khu nghỉ dưỡng cao cấp toàn cầu.', descEn: 'Marriott International hotel group with over 30 premium hotel and resort brands worldwide.', founded: 1927, hq: 'Bethesda, Maryland, Mỹ', statLabelVi: 'Khách sạn toàn cầu', statLabelEn: 'Hotels worldwide', statValue: '8,900+ khách sạn', projectsVi: ['JW Marriott Hà Nội – vườn cảnh quan & sảnh ngoài trời', 'Sheraton Đà Nẵng – cảnh quan bãi biển & hồ bơi', 'Marriott Bonvoy Phú Quốc – tiểu cảnh nhiệt đới'], projectsEn: ['JW Marriott Hanoi – outdoor garden & lobby landscape', 'Sheraton Da Nang – beach & pool landscape', 'Marriott Bonvoy Phu Quoc – tropical softscape'], highlightVi: 'Tập đoàn khách sạn lớn nhất thế giới, hiện diện tại 141 quốc gia.', highlightEn: "World's largest hotel group, present in 141 countries.", order: 16 },
  { name: 'Hyatt', sector: 'Khách sạn Quốc tế', sectorEn: 'International Hotel', descVi: 'Tập đoàn Hyatt sở hữu nhiều thương hiệu khách sạn cao cấp, đang mở rộng mạnh tại Việt Nam.', descEn: 'Hyatt Corporation owns multiple premium hotel brands, with strong expansion in Vietnam.', founded: 1957, hq: 'Chicago, Illinois, Mỹ', statLabelVi: 'Khách sạn toàn cầu', statLabelEn: 'Hotels worldwide', statValue: '1,150+ khách sạn', projectsVi: ['Park Hyatt Sài Gòn – vườn sân thượng & tiểu cảnh', 'Hyatt Regency Đà Nẵng – bãi biển & hồ bơi ngoài trời', 'Alila Hội An – vườn nhiệt đới hữu cơ & mặt nước'], projectsEn: ['Park Hyatt Saigon – rooftop garden & softscape', 'Hyatt Regency Da Nang – beach & outdoor pool landscape', 'Alila Hoi An – organic tropical garden & water features'], highlightVi: 'Thương hiệu Alila (thuộc Hyatt) nổi tiếng tại Hội An với triết lý thiên nhiên bền vững.', highlightEn: 'Alila brand (under Hyatt) is renowned in Hoi An for its sustainable nature philosophy.', order: 17 },
  { name: 'Seava Hồ Tràm', sector: 'Khu nghỉ dưỡng', sectorEn: 'Resort', descVi: 'Khu nghỉ dưỡng biển Seava tại Hồ Tràm, Bà Rịa – Vũng Tàu với cảnh quan thiên nhiên tuyệt đẹp.', descEn: 'Seava seaside resort at Ho Tram, Ba Ria – Vung Tau with stunning natural landscape.', founded: 2018, hq: 'Hồ Tràm, Bà Rịa – Vũng Tàu, Việt Nam', statLabelVi: 'Đường bờ biển sở hữu', statLabelEn: 'Private beachfront', statValue: '1.2 km bãi biển', projectsVi: ['Seava Beach Resort – cảnh quan bờ biển & hồ bơi tràn bờ', 'Khu villa Seava – vườn nhiệt đới riêng từng căn', 'Bãi biển riêng – cây dừa & thảm cỏ ven biển'], projectsEn: ['Seava Beach Resort – beachfront & infinity pool landscape', 'Seava Villas – individual tropical villa gardens', 'Private beach – coconut palms & coastal lawn works'], highlightVi: 'Resort biển cao cấp mới nổi tại Hồ Tràm, sở hữu 1.2 km bờ biển riêng.', highlightEn: 'Rising premium beach resort in Ho Tram with 1.2 km of private beachfront.', order: 18 },
  { name: 'TonkinLand', sector: 'Bất động sản', sectorEn: 'Real Estate', descVi: 'TonkinLand – nhà phát triển bất động sản mới nổi tại miền Bắc và miền Trung Việt Nam.', descEn: 'TonkinLand – emerging real estate developer in Northern and Central Vietnam.', founded: 2015, hq: 'Hà Nội, Việt Nam', statLabelVi: 'Dự án đang triển khai', statLabelEn: 'Active projects', statValue: '8 dự án', projectsVi: ['Tonkin Lotus Lake – cảnh quan hồ sen & khu dân cư', 'The Eden Rose Hà Nội – sân vườn & hành lang xanh', 'TonkinLand Nghệ An – cây xanh khu đô thị mới'], projectsEn: ['Tonkin Lotus Lake – lotus lake & residential landscape', 'The Eden Rose Hanoi – gardens & green corridors', 'TonkinLand Nghe An – new urban greenery'], highlightVi: 'Đang mở rộng nhanh sang các tỉnh miền Trung với nhiều dự án quy mô lớn.', highlightEn: 'Rapidly expanding into Central Vietnam provinces with large-scale projects.', order: 19 },
];

const jobPositions = [
  { titleVi: 'Kiến Trúc Sư Cảnh Quan', titleEn: 'Landscape Architect', typeVi: 'Toàn thời gian', typeEn: 'Full-time', locationVi: 'Đà Nẵng / Công trường', locationEn: 'Da Nang / On-site', descVi: 'Chịu trách nhiệm lập hồ sơ thiết kế cảnh quan cho các dự án resort, sân golf, khu đô thị. Phối hợp với kỹ sư và đội thi công để đảm bảo chất lượng và tiến độ. Yêu cầu tốt nghiệp ngành Kiến trúc Cảnh quan hoặc liên quan, có ít nhất 2 năm kinh nghiệm, thành thạo AutoCAD và SketchUp.', descEn: 'Responsible for landscape design documentation for resort, golf course, and urban projects. Coordinate with engineers and construction teams to ensure quality and schedule. Requires a degree in Landscape Architecture or related field, at least 2 years of experience, proficiency in AutoCAD and SketchUp.', order: 0 },
  { titleVi: 'Giám Sát Thi Công Sân Golf', titleEn: 'Golf Course Construction Supervisor', typeVi: 'Toàn thời gian', typeEn: 'Full-time', locationVi: 'Trên toàn quốc', locationEn: 'Nationwide', descVi: 'Giám sát trực tiếp quá trình thi công cảnh quan và hệ thống tưới tiêu tại các dự án sân golf. Kiểm soát chất lượng cỏ, cây trồng và hệ thống tưới Rainbird. Yêu cầu có kinh nghiệm thi công sân golf hoặc cảnh quan ngoài trời tối thiểu 3 năm, sẵn sàng di chuyển theo dự án.', descEn: 'Directly supervise landscape construction and irrigation systems at golf course projects. Quality control for turf, planting, and Rainbird irrigation systems. Requires minimum 3 years of golf course or outdoor landscape construction experience, willing to travel to project sites.', order: 1 },
  { titleVi: 'Chỉ Huy Trưởng Cảnh Quan', titleEn: 'Site Manager – Landscape', typeVi: 'Toàn thời gian', typeEn: 'Full-time', locationVi: 'Đà Nẵng / Miền Trung', locationEn: 'Da Nang / Central Vietnam', descVi: 'Quản lý toàn bộ hoạt động thi công tại hiện trường, điều phối nhân lực và vật tư, báo cáo tiến độ cho ban giám đốc. Yêu cầu tốt nghiệp kỹ sư xây dựng hoặc cảnh quan, tối thiểu 5 năm kinh nghiệm quản lý công trình, kỹ năng lãnh đạo và đọc bản vẽ tốt.', descEn: 'Manage all on-site construction activities, coordinate manpower and materials, report progress to management. Requires a degree in Civil or Landscape Engineering, minimum 5 years of site management experience, strong leadership skills and ability to read construction drawings.', order: 2 },
  { titleVi: 'Công Nhân Thi Công Cảnh Quan', titleEn: 'Landscape Construction Worker', typeVi: 'Toàn thời gian', typeEn: 'Full-time', locationVi: 'Nhiều công trường', locationEn: 'Multiple sites', descVi: 'Thực hiện các công việc thi công cảnh quan như trồng cây, lát đá, lắp đặt hệ thống tưới và công trình ngoại thất. Không yêu cầu bằng cấp, ưu tiên có kinh nghiệm thi công. Được đào tạo thực tế tại công trường, phụ cấp đi lại và ăn ở đầy đủ.', descEn: 'Carry out landscape construction tasks including planting, paving, irrigation installation, and outdoor structures. No formal degree required; experience preferred. On-the-job training provided, with full travel and accommodation allowances.', order: 3 },
  { titleVi: 'Nhân Viên Phát Triển Kinh Doanh', titleEn: 'Business Development Executive', typeVi: 'Toàn thời gian', typeEn: 'Full-time', locationVi: 'Đà Nẵng', locationEn: 'Da Nang', descVi: 'Tìm kiếm và phát triển các cơ hội kinh doanh mới trong lĩnh vực cảnh quan, tiếp cận khách hàng B2B là chủ đầu tư và nhà thầu. Yêu cầu ít nhất 2 năm kinh nghiệm bán hàng B2B, kỹ năng giao tiếp và đàm phán tốt, ưu tiên có mạng lưới trong ngành xây dựng và bất động sản.', descEn: 'Identify and develop new business opportunities in the landscape sector, targeting B2B clients such as investors and contractors. Requires at least 2 years of B2B sales experience, strong communication and negotiation skills, with preference for candidates with a network in construction and real estate.', order: 4 },
];

const newsArticles = [
  { slug: 'fam-landscape-2024-highlights', titleVi: 'FAM Landscape – Điểm Nổi Bật 2024', titleEn: 'FAM Landscape – 2024 Highlights', summaryVi: 'Nhìn lại những dự án tiêu biểu và cột mốc quan trọng của FAM Landscape trong năm 2024.', summaryEn: 'A look back at FAM Landscape\'s standout projects and milestones throughout 2024.', image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80', published: true, publishedAt: new Date('2024-12-20') },
  { slug: 'golf-course-landscape-trends-2025', titleVi: 'Xu Hướng Cảnh Quan Sân Golf 2025', titleEn: 'Golf Course Landscape Trends 2025', summaryVi: 'Những xu hướng thiết kế và thi công cảnh quan sân golf nổi bật trong năm 2025 theo góc nhìn chuyên gia FAM.', summaryEn: 'Standout golf course landscape design and construction trends for 2025, from FAM\'s expert perspective.', image: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=80', published: true, publishedAt: new Date('2025-01-15') },
  { slug: 'sustainable-landscape-practices', titleVi: 'Cảnh Quan Bền Vững – Hướng Đi Của FAM', titleEn: 'Sustainable Landscaping – FAM\'s Approach', summaryVi: 'FAM Landscape ứng dụng các tiêu chuẩn ISO và thực hành bền vững trong mọi dự án cảnh quan.', summaryEn: 'FAM Landscape applies ISO standards and sustainable practices across all landscape projects.', image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80', published: true, publishedAt: new Date('2025-02-10') },
];

async function main() {
  console.log('Seeding projects...');
  for (const p of projects) {
    const { images, ...data } = p;
    await prisma.project.upsert({
      where: { slug: data.slug },
      update: {},
      create: {
        ...data,
        area: (data as any).area ?? null,
        published: true,
        images: {
          create: images.map((url, i) => ({ url, order: i })),
        },
      },
    });
  }
  console.log(`Done — ${projects.length} projects seeded.`);

  const heroCount = await prisma.heroSlide.count();
  if (heroCount === 0) {
    await prisma.heroSlide.createMany({ data: heroSlides });
    console.log(`Seeded ${heroSlides.length} hero slides.`);
  }

  const serviceCount = await prisma.service.count();
  if (serviceCount === 0) {
    await prisma.service.createMany({ data: services });
    console.log(`Seeded ${services.length} services.`);
  }

  const timelineCount = await prisma.timelineItem.count();
  if (timelineCount === 0) {
    await prisma.timelineItem.createMany({ data: timelineItems });
    console.log(`Seeded ${timelineItems.length} timeline items.`);
  }

  const partnerCount = await prisma.partner.count();
  if (partnerCount === 0) {
    await prisma.partner.createMany({ data: partners });
    console.log(`Seeded ${partners.length} partners.`);
  }

  const jobCount = await prisma.jobPosition.count();
  if (jobCount === 0) {
    await prisma.jobPosition.createMany({ data: jobPositions });
    console.log(`Seeded ${jobPositions.length} job positions.`);
  }

  for (const article of newsArticles) {
    await prisma.newsArticle.upsert({
      where: { slug: article.slug },
      update: {},
      create: article,
    });
  }
  console.log(`Seeded ${newsArticles.length} news articles.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
